# Generated by Django 5.2 on 2025-05-25 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuadrilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('LLENO', 'Lleno en su totalidad'), ('MEDIO', 'A la mitad de su capacidad'), ('VACIO', 'Vaciado por completo'), ('DESCOMPUESTO', 'Descompuesto o no disponible'), ('OCUPADO', 'Ocupado por otra entidad'), ('DISPONIBLE', 'Disponible para asignarse')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Incendio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('clave', models.CharField(max_length=20)),
                ('fechaIncio', models.DateTimeField()),
                ('fechaCierre', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoJornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreJornada', models.CharField(choices=[('MATUTINA', 'matutina'), ('VESPERTINA', 'vespertina'), ('NOCTURNA', 'nocturna'), ('ACUMULADA', 'acumulada')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoUsuario', models.CharField(choices=[('COMANDANTE', 'comandante de incidentes'), ('CUADRILLA', 'jefe de cuadrilla'), ('COMBATIENTE', 'combatiente de incendios'), ('OBSERVADOR', 'observador-vigilante de zona'), ('TECNICO', 'técnico de maquinaría y planeación'), ('MEDICO', 'médico o paramedico')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('latitud', models.FloatField(max_length=20)),
                ('longitud', models.FloatField(max_length=20)),
                ('radio', models.FloatField(default=1)),
                ('fecha', models.DateTimeField()),
                ('incendio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Okoyotl.incendio')),
            ],
        ),
        migrations.CreateModel(
            name='Recursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('estadoRecurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Okoyotl.estadorecurso')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apPaterno', models.CharField(max_length=100)),
                ('apMaterno', models.CharField(max_length=100)),
                ('edad', models.SmallIntegerField()),
                ('curp', models.CharField(max_length=255)),
                ('numTel', models.BigIntegerField()),
                ('email', models.CharField(max_length=255)),
                ('disponible', models.BooleanField(default=False)),
                ('tipoJornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Okoyotl.tipojornada')),
                ('tipoPuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Okoyotl.tipopuesto')),
            ],
            options={
                'unique_together': {('tipoPuesto', 'tipoJornada')},
            },
        ),
        migrations.CreateModel(
            name='RelPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAsignado', models.DateTimeField()),
                ('cuadrilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Okoyotl.cuadrilla')),
                ('incendio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Okoyotl.incendio')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Okoyotl.personal')),
            ],
            options={
                'unique_together': {('incendio', 'personal', 'cuadrilla')},
            },
        ),
        migrations.CreateModel(
            name='RelRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('incendio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Okoyotl.incendio')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Okoyotl.recursos')),
            ],
            options={
                'unique_together': {('incendio', 'recurso')},
            },
        ),
    ]
